	ORG $0
FD	RMB 1
SD	RMB 1
TD	RMB 1

TEMP	RMB 1
TEMP1	RMB 1

	ORG $10
DAT	RMB 1

	ORG $100

	LDAA	DAT	;CHANGE THIS VALUE TO TEST

*---------- COMPUTE THE FIRST DIGIT (HUNDREDS VALUE)

FIRST	TAB		; FOR DIVISION WE NEED THE DAT VALUE IN ACCB
	CLRA		; CLEAR A SO THAT D = 00HL (H=HIGH NIBBLE OF DAT, L= LOW NIBBLE OF DAT)

	LDX	#100	;IDIV DIVIDES D WITH X. RESULT GOES INTO X AND REMAINDER IN D
	IDIV		;DIVIDE THE VALUE BY 100
	XGDX		;RESULT IS IN X, SO GET IT INTO D

	STD	TEMP	;STORE INTO A TEMPORARY LOCATION
	
	LDAA	TEMP1   ;LOAD A WITH THE RESULT (IN THE LOWER BYTE OF TEMP)

	STAA	FD	;STORE THE FIRST DECIMAL DIGIT INTO FD
	
	BEQ	SECOND	;IF FD = 0 THEN FIGURE OUT WHAT THE SECOND DIGIT IS
	
	LDAA	DAT

			;IF THE FD > 0 THEN WE HAVE A 1XX OR A 2XX DECIMAL
L1	SUBA	#100	;SUBTRACT 100 FROM THE HEX DATA  
	CMPA	#100	
	BHI	L1	;UNTIL IT IS LOWER THEN 100 (BHI IS BRANCH IF HIGHER)
	BRA	SECOND1	;NOW A HOLDS THE XX VALUE WITH THE MOST SIGNIFICAN DIGIT REMOVED

*---------- COMPUTE THE SECOND DIGIT (TENS VALUE)

SECOND	LDAA	DAT	
SECOND1	TAB		;NO NEED TO LOAD A WITH DAT, A HAS THE VALUE WE NEED FROM L1 LOOP 
	CLRA
			;SAME OPERATIONS AS ABOVE
	LDX	#10	;EXCEPT WE DIVIDE BY 10
	IDIV
	XGDX
	
	STD	TEMP

	LDAA	TEMP1

	STAA	SD	;STORE THE SECOND DECIMAL DIGIT INTO SD

	BEQ	THIRD

	LDAA	DAT

L2	SUBA	#10	; SUBTRACT 10 FROM THE ORIGINAL VALUE UNTIL YOU HAVE THE LAST DIGIT
	CMPA	#10
	BHI	L2
	BRA	THIRD


THIRD	STAA	TD	;STORE THE THIRD DECIMAL DIGIT INTO TD


	SWI